name: krishi_sakha
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.8.1
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # GGUF model runner dependencies
  fllama:
    git:
      url: https://github.com/Telosnex/fllama.git
      ref: main
  file_picker: ^8.1.2
  image_picker: ^1.2.0
  path_provider: ^2.1.4
  provider: ^6.1.2
  file_selector: ^1.0.3
  shared_preferences: ^2.5.3
  lottie: ^3.3.1
  go_router: ^16.0.0
  permission_handler: ^12.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  uuid: ^4.5.1
  fluttertoast: ^8.2.12
  path: ^1.9.1
  supabase_flutter: ^2.9.1
  flutter_dotenv: ^5.2.1
  logger: ^2.6.2
  http: ^1.5.0
  flutter_markdown: ^0.7.7+1
  flutter_tts: ^4.2.3
  speech_to_text: ^7.3.0
  geolocator: ^13.0.2
  geocoding: ^3.0.0
  intl: ^0.20.2
  location: ^8.0.1
  url_launcher: ^6.3.2
  youtube_player_flutter: ^9.1.1
  tflite_flutter: ^0.12.1
  image: ^4.2.1
  webview_flutter: ^4.13.0
  rename_app: ^1.6.5
  animate_do: ^3.3.4
  shimmer: ^3.0.0
  flutter_sound: ^9.29.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.7
  hive_generator: ^2.0.1

flutter:

  generate: true
  uses-material-design: true

  assets:
    - assets/lottie/
    - assets/images/
    - assets/
    - assets/model/tamato/
    - .env
